machine:
  network:
    hostname: control-0
    interfaces:
    - interface: eth0
      # Flat LAN — single management interface.
      # VIP 192.168.5.10 floats here on whichever control-plane node is leader.
      dhcp: false
      addresses:
      - 192.168.5.11/16
      routes:
      - network: 0.0.0.0/0
        gateway: 192.168.0.1
      vip:
        ip: 192.168.5.10
