machine:
  network:
    hostname: worker-3
    interfaces:
    - interface: eth0
      # Flat LAN — single management interface.
      dhcp: false
      addresses:
      - 192.168.5.24/16
      routes:
      - network: 0.0.0.0/0
        gateway: 192.168.0.1
