options {
    directory "/var/cache/bind";

    // Forward queries not in our zone to upstream DNS
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };

    dnssec-validation auto;

    listen-on { any; };
    listen-on-v6 { any; };

    allow-query { any; };
    allow-recursion { any; };
};

// Forward zone for hierocracy.local
zone "hierocracy.home" {
    type master;
    file "/etc/bind/zones/db.hierocracy.home";
};

// Reverse zone for 192.168.1.0/24
zone "1.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/db.192.168.1";
};

// Reverse zone for 172.20.1.0/24
zone "1.20.172.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/db.172.20.1";
};  