machine:
  udev:
    rules:
      - SUBSYSTEM=="block", ACTION=="add", RUN+="/sbin/pvscan --cache %N"
  network:
    hostname: worker-3
    interfaces:
    - interface: eth0
      dhcp: true
    - interface: eth1
      dhcp: false
      addresses:
      - 172.20.0.113/16
