export mac_prefix="6A:69:11:AA:00"
export control_0_mac="${mac_prefix}:A1"
export control_1_mac="${mac_prefix}:A2"
export control_2_mac="${mac_prefix}:A3"
export data_0_mac="${mac_prefix}:A4"
export data_1_mac="${mac_prefix}:A5"
export data_2_mac="${mac_prefix}:A6"
export data_3_mac="${mac_prefix}:A7"

export extern_mac_prefix="6A:69:11:AA:10"
export control_0_extern_mac="${extern_mac_prefix}:A1"
export control_1_extern_mac="${extern_mac_prefix}:A2"
export control_2_extern_mac="${extern_mac_prefix}:A3"
export data_0_extern_mac="${extern_mac_prefix}:A4"
export data_1_extern_mac="${extern_mac_prefix}:A5"
export data_2_extern_mac="${extern_mac_prefix}:A6"
export data_3_extern_mac="${extern_mac_prefix}:A7"
